# Generated by Django 3.2.16 on 2022-12-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_alter_user_accounts_following'),
        ('account', '0003_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
