# Generated by Django 3.2.16 on 2023-01-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_dob_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='MM/DD/YYYY', null=True),
        ),
    ]
