# Generated by Django 3.2.16 on 2022-12-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_post_created_7a8cc9_idx',
        ),
    ]
