# Generated by Django 3.2.16 on 2022-12-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_accounts_following'),
        ('post', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
