# Generated by Django 3.2.16 on 2022-12-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_alter_user_accounts_following'),
        ('post', '0012_auto_20221222_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
