# Generated by Django 3.2.16 on 2022-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_caption_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption_edited_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
